spring:
  application:
    name: egde-service

  cloud:
    gateway:
      routes:
      - id: catalog-service
        uri: ${CATALOG_SERVICE_URL:http://localhost:9001}/books
        predicates:
        - Path=/books/**
      - id: order-service
        uri: ${ORDER_SERVICE_URL:http://localhost:9002}/orders
        predicates:
        - Path=/orders/**

  lifecycle:
    timeout-per-shutdown-phase: 15s

server:
  port: 9000
  netty:
    connection-timeout: 2s
    idle-timeout: 15s
  shutdown: graceful